version: '3.3'

services:
  habit:
    build: ./habit-service/
    container_name: habit
    depends_on:
      - dbhabit
      - rabbitmq
    expose:
      - 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbhabit:5432/habit
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_RABBITMQ_HOST=rabbitmq
  dbhabit:
    image: 'postgres:13.1-alpine'
    container_name: dbhabit
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=habit
    expose:
      - 5432
  auth:
    build: ./auth-service/
    container_name: auth
    depends_on:
      - dbauth
      - rabbitmq
    expose:
      - 8083
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbauth:5432/habitauth
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_RABBITMQ_HOST=rabbitmq
  dbauth:
    image: 'postgres:13.1-alpine'
    container_name: dbauth
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=habitauth
    expose:
      - 5432
  city:
    build: ./city-service/
    container_name: city
    depends_on:
      - dbcity
      - rabbitmq
      - cache
    expose:
      - 8082
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbcity:5432/habitcity
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_REDIS_HOST=cache
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=password
  dbcity:
    image: 'postgres:13.1-alpine'
    container_name: dbcity
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=habitcity
    expose:
      - 5432
  gamification:
    build: ./gamification-service/
    container_name: gamification
    depends_on:
      - dbgamification
      - rabbitmq
    expose:
      - 8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbgamification:5432/habitgame
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_RABBITMQ_HOST=rabbitmq
  dbgamification:
    image: 'postgres:13.1-alpine'
    container_name: dbgamification
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=habitgame
    expose:
      - 5432
  gateway:
    build: ./gateway/
    container_name: gateway
    ports:
      - "8000:8000"
    depends_on: 
      - habit
      - auth
      - city
      - gamification
    environment:
      SPRING_PROFILES_ACTIVE: path
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://habit:8080
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: 'habit'
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: 'Path=/habit/**,/context/**'
      SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERs[0]: 'AuthenticationFilterFactory'
      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: http://gamification:8081
      SPRING_CLOUD_GATEWAY_ROUTES[1]_ID: 'gamification'
      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]: 'Path=/experience/**'
      SPRING_CLOUD_GATEWAY_ROUTES[1]_FILTERs[0]: 'AuthenticationFilterFactory'
      SPRING_CLOUD_GATEWAY_ROUTES[2]_URI: http://city:8082
      SPRING_CLOUD_GATEWAY_ROUTES[2]_ID: 'city'
      SPRING_CLOUD_GATEWAY_ROUTES[2]_PREDICATES[0]: 'Path=/equipment/**,/shop/**,/craft,/city/**'
      SPRING_CLOUD_GATEWAY_ROUTES[2]_FILTERs[0]: 'AuthenticationFilterFactory'
      SPRING_CLOUD_GATEWAY_ROUTES[3]_URI: http://auth:8083
      SPRING_CLOUD_GATEWAY_ROUTES[3]_ID: 'auth'
      SPRING_CLOUD_GATEWAY_ROUTES[3]_PREDICATES[0]: 'Path=/authenticate,/register'
      SPRING_CLOUD_GATEWAY_GLOBALCORS_CORS-CONFIGURATIONS['[/**]']_ALLOWEDORIGINS: http://localhost
  habitfrontend:
    container_name: habitfrontend
    build: ./frontend/
    ports:
      - "80:80"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local
