server:
    port: 8000
spring:
    cloud:
        gateway:
            routes:
                - id: habit
                  uri: http://localhost:8080
                  predicates:
                    - Path=/habit/**,/context/**
                - id: gamification
                  uri: http://localhost:8081
                  predicates:
                    - Path=/experience/**
                - id: city
                  uri: http://localhost:8082
                  predicates:
                    - Path=/equipment/**
            globalcors:
                cors-configurations:
                    '[/**]':
                        allowedOrigins: "http://localhost:4200"
                        allowedHeaders: "*"
                        allowedMethods:
                            - "GET"
                            - "POST"
                            - "OPTIONS"
logging:
    level:
        org.springframework.cloud.gateway.handler.predicate: trace
jwt:
    secret: "secret"